"""empty message

Revision ID: d6768e2a8a03
Revises: 5ad164e2a580
Create Date: 2021-09-25 14:27:40.120596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6768e2a8a03'
down_revision = '5ad164e2a580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('show', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'show', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'show', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.alter_column('show', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_table('“show”',
    sa.Column('“id”', sa.INTEGER(), server_default=sa.text('nextval(\'"“show”_“id”_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('“artist_id”', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('“venue_id”', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('“start_time”', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('“id”', name='“show”_pkey')
    )
    # ### end Alembic commands ###
